### list
GET http://localhost:9129/list?app=app1&env=dev&ns=public

### update
POST http://localhost:9129/update?app=app1&env=dev&ns=public
Content-Type: application/json

{
  "cat.a": "avvvv",
  "cat.b": "c400",
  "cat.c": "d300",
  "cat.d": "ddd"
}

### version
GET http://localhost:9129/version?app=app1&env=dev&ns=public

### demo
GET http://localhost:8888/demo?app=app1&env=dev&ns=public

### update catrpc config
POST http://localhost:9129/update?app=app1&env=dev&ns=public
Content-Type: application/json

{
  "catrpc.provider.metas.dc": "sz222",
  "catrpc.provider.metas.gray": "false",
  "catrpc.provider.metas.unit": "S008",
  "catrpc.provider.metas.tc": 27
}